# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-personal_cheatsheet',
                'doc_host': 'https://itaysegev.github.io',
                'git_url': 'https://github.com/itaysegev/nbdev-personal_cheatsheet',
                'lib_path': 'nbdev_personal_cheatsheet'},
  'syms': { 'nbdev_personal_cheatsheet.core': { 'nbdev_personal_cheatsheet.core.foo': ( 'core.html#foo',
                                                                                        'nbdev_personal_cheatsheet/core.py')}}}
